site_name: YAP Prolog Reference Manual
site_url: https://www.dcc.fc.up.pt/YAP
use_directory_urls: false
theme:
  name: 'material'
  logo: 'images/favicon.ico'
  features:
    - navigation.instant
    - navigation.trackbig
    - navigation.sections
    - navigation.expand
    - navigation.tabs
    - toc.integrate  
    - header.autohide  
    - logo: favicon.ico
    - content.tooltips
extra_javascript:
    - javascripts/highlight.min.js
plugins:
  - search
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
nav:
   - Home: index.md
   - INSTALL: INSTALL.md
   - run: CALLING_YAP.md
   - Core Built-ins: group___builtins.md
   - Programming: group___y_a_p_programming.md
   - Extensions: group___yap_extensions.md
   - Library: group___y_a_p_library.md
   - packages: group___y_a_p_packages.md
   - Foreign Language Interface : group___y_a_p_a_p_i.md


