site_name: YAP Prolog Reference Manual
site_url: https://www.dcc.fc.up.pt/YAP
use_directory_urls: true
theme:
  name: 'material'
  logo: 'images/favicon.ico'
  features:
    - navigation.instant
    - navigation.trackbig
    - navigation.sections
    - navigation.expand
    - navigation.tabs
    - toc.integrate  
    - header.autohide  
    - logo: favicon.ico
    - content.tooltips
extra_javascript:
    - javascripts/highlight.min.js
plugins:
  - search
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
nav:
   - Home: index.md
   - INSTALL: INSTALL.md
   - run: run.md
   - Core Built-ins: group__Builtins.md
   - Programming: group__YAPProgramming.md
   - Extensions: group__YapExtensions.md
   - Library: group__YAPLibrary.md
   - packages: packages.md
   - Foreign Language Interface : mox/group__YAPFLI.md 

