site_name: YAP Prolog Reference Manual
site_url: https://www.dcc.fc.up.pt/YAP
use_directory_urls: false
theme:
  name: 'readthedocs'
  highlightjs: true
  hljs_languages:
    - prolog
  logo: 'images/favicon.ico'
plugins:
  - search
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
nav:
   - Home: index.md
   - INSTALL: INSTALL.md
   - run: CALLING_YAP.md
   - Core Built-ins: Builtins.md
   - Programming: YAPProgramming.md
   - Extensions: YapExtensions.md
   - Library: YAPLibrary.md
   - packages: YAPPackages.md
   - Foreign Language Interface : YAPAPI.md


